# Generated by Django 3.2.9 on 2021-12-07 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='heading',
            old_name='desc',
            new_name='desc1',
        ),
        migrations.AddField(
            model_name='heading',
            name='desc2',
            field=models.TextField(blank=True, null=True),
        ),
    ]
